# POST https://localhost:5001/api/categories
# Content-Type: application/json

# {
#     "Name": "Cars"
# }


# PUT https://localhost:5001/api/categories/200
# Content-Type: application/json

# {
#     "Name": "NOTEBOOKS"
# }

# DELETE https://localhost:5001/api/categories/100


# POST https://localhost:5001/api/products
# Content-Type: application/json

# {
#     "ProductName": "test",
#     "ProductCount": 111,
#     "CategoryId": 1000
# }


# GET https://localhost:5001/api/products


# DELETE  https://localhost:5001/api/products/1001

# PUT https://localhost:5001/api/products/1002
# Content-Type: application/json

# {
#     "productName": "LG",
#     "productCount": 1,
#     "categoryId": 1003
# }






# POST https://localhost:5001/api/auth
# Content-Type: application/json

# {
#     "login":"admin",
#     "password":"admin"
# }


GET https://localhost:5001/api/products